LangString addOrReinstall ${LANG_JAPANESE} "修復または再インストール"
LangString alreadyInstalled ${LANG_JAPANESE} "すでにインストールされています"
LangString alreadyInstalledLong ${LANG_JAPANESE} "${PRODUCTNAME} ${VERSION} は、すでにインストールされています。続行する操作を選んで、[次へ] をクリックしてください。"
LangString appRunning ${LANG_JAPANESE} "${PRODUCTNAME} が起動中です。終了してから、もう一度お試しください。"
LangString appRunningOkKill ${LANG_JAPANESE} "${PRODUCTNAME} が起動中です。$\nOK をクリックすると終了します。"
LangString chooseMaintenanceOption ${LANG_JAPANESE} "続行する操作を選んでください。"
LangString choowHowToInstall ${LANG_JAPANESE} "${PRODUCTNAME} のインストール方法を選んでください。"
LangString createDesktop ${LANG_JAPANESE} "デスクトップ ショートカットを作成する"
LangString dontUninstall ${LANG_JAPANESE} "アンインストールしない"
LangString dontUninstallDowngrade ${LANG_JAPANESE} "アンインストールしない（このインストーラーでは、アンインストールせずにダウングレードすることはできません）"
LangString failedToKillApp ${LANG_JAPANESE} "${PRODUCTNAME} を終了できませんでした。アプリを閉じてから、もう一度お試しください。"
LangString installingWebview2 ${LANG_JAPANESE} "WebView2 をインストールしています..."
LangString newerVersionInstalled ${LANG_JAPANESE} "${PRODUCTNAME} の新しいバージョンが、すでにインストールされています。古いバージョンを上書きインストールすることはおすすめしません。インストールする場合は、現在のバージョンを先にアンインストールしてください。続行する操作を選んで、[次へ] をクリックしてください。"
LangString older ${LANG_JAPANESE} "以前の"
LangString olderOrUnknownVersionInstalled ${LANG_JAPANESE} "$R4 バージョンの ${PRODUCTNAME} が、すでにインストールされています。インストールする前に、現在のバージョンをアンインストールすることをおすすめします。続行する操作を選んで、[次へ] をクリックしてください。"
LangString silentDowngrades ${LANG_JAPANESE} "このインストーラーではダウングレードが無効になっているため、サイレントインストールは続行できません。通常のインストーラーをご利用ください。$\n"
LangString unableToUninstall ${LANG_JAPANESE} "アンインストールできませんでした。"
LangString uninstallApp ${LANG_JAPANESE} "${PRODUCTNAME} をアンインストールする"
LangString uninstallBeforeInstalling ${LANG_JAPANESE} "現在のバージョンをアンインストールしてからインストールする"
LangString unknown ${LANG_JAPANESE} "不明な"
LangString webview2AbortError ${LANG_JAPANESE} "WebView2 のインストールに失敗しました。${PRODUCTNAME} を起動するには WebView2 が必要です。インストーラーを起動し直して、もう一度お試しください。"
LangString webview2DownloadError ${LANG_JAPANESE} "WebView2 のダウンロードに失敗しました: $0"
LangString webview2DownloadSuccess ${LANG_JAPANESE} "WebView2 インストーラーのダウンロードが完了しました"
LangString webview2Downloading ${LANG_JAPANESE} "WebView2 インストーラーをダウンロードしています..."
LangString webview2InstallError ${LANG_JAPANESE} "WebView2 のインストールに失敗しました。終了コード: $1"
LangString webview2InstallSuccess ${LANG_JAPANESE} "WebView2 のインストールが完了しました"
LangString deleteAppData ${LANG_JAPANESE} "設定や保存データも削除する"
LangString finishAdminNotice ${LANG_JAPANESE} "インストールが完了しました。$\r$\nパケットキャプチャ機能を使うには、管理者として起動する必要があります。$\r$\nスタートメニューまたはデスクトップのショートカットを右クリックし、[管理者として実行] を選んで起動してください。"
